import { useState } from 'react';
import EndpointCard, { Endpoint } from '@/components/EndpointCard';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Search } from 'lucide-react';

export default function APIReference() {
  const [searchQuery, setSearchQuery] = useState('');

  const endpoints: Endpoint[] = [
    {
      name: 'User Login',
      method: 'POST',
      path: '/api/auth/login/',
      description: 'Authenticates a user and returns JWT tokens.',
      authentication: 'None',
      requestBody: {
        filename: 'login.json',
        language: 'json',
        code: '{\n  "email": "user@example.com",\n  "password": "yourpassword"\n}'
      },
      responseBody: {
        filename: 'login_response.json',
        language: 'json',
        code: '{\n  "access": "eyJhbGciOiJIUzI1Ni...",\n  "refresh": "eyJhbGciOiJIUzI1Ni..."\n}'
      },
    },
    {
      name: 'Get User Profile',
      method: 'GET',
      path: '/api/users/me/',
      description: 'Retrieves the authenticated user\'s profile.',
      authentication: 'JWT',
      responseBody: {
        filename: 'user_profile.json',
        language: 'json',
        code: '{\n  "id": 1,\n  "email": "user@example.com",\n  "first_name": "John",\n  "last_name": "Doe",\n  "credit_balance": "100.50"\n}'
      },
    },
    {
      name: 'List Projects',
      method: 'GET',
      path: '/api/projects/',
      description: 'Returns a list of projects owned by the authenticated user.',
      authentication: 'JWT',
      queryParams: [
        { name: 'search', type: 'string', description: 'Search projects by name or description', required: false },
        { name: 'limit', type: 'integer', description: 'Number of results to return per page', required: false },
      ],
      responseBody: {
        filename: 'projects_list.json',
        language: 'json',
        code: '[\n  {\n    "id": 1,\n    "name": "My First Project",\n    "slug": "my-first-project",\n    "created_at": "2023-01-01T12:00:00Z"\n  }\n]'
      },
    },
    {
      name: 'Create Project',
      method: 'POST',
      path: '/api/projects/',
      description: 'Creates a new project for the authenticated user.',
      authentication: 'JWT',
      requestBody: {
        filename: 'create_project.json',
        language: 'json',
        code: '{\n  "name": "New Awesome Project",\n  "description": "A project generated by Buildify"\n}'
      },
      responseBody: {
        filename: 'project_detail.json',
        language: 'json',
        code: '{\n  "id": 2,\n  "name": "New Awesome Project",\n  "slug": "new-awesome-project",\n  "created_at": "2023-01-02T14:30:00Z"\n}'
      },
    },
    {
      name: 'Get Project Details',
      method: 'GET',
      path: '/api/projects/{slug}/',
      description: 'Retrieves details for a specific project.',
      authentication: 'JWT',
      pathParams: [
        { name: 'slug', type: 'string', description: 'The unique slug of the project' },
      ],
      responseBody: {
        filename: 'project_detail.json',
        language: 'json',
        code: '{\n  "id": 1,\n  "name": "My First Project",\n  "slug": "my-first-project",\n  "description": "This is a description of my first project.",\n  "files": {\n    "src/App.tsx": "import React from \'react\';..."\n  },\n  "github_repo": null,\n  "preview_url": null,\n  "created_at": "2023-01-01T12:00:00Z",\n  "updated_at": "2023-01-01T12:00:00Z"\n}'
      },
    },
    {
      name: 'Update Project File',
      method: 'PUT',
      path: '/api/projects/{slug}/files/',
      description: 'Updates the content of a specific file within a project.',
      authentication: 'JWT',
      pathParams: [
        { name: 'slug', type: 'string', description: 'The unique slug of the project' },
      ],
      requestBody: {
        filename: 'update_file.json',
        language: 'json',
        code: '{\n  "path": "src/components/Button.tsx",\n  "content": "// New content for the button component"\n}'
      },
      responseBody: {
        filename: 'file_update_response.json',
        language: 'json',
        code: '{\n  "message": "File updated successfully",\n  "path": "src/components/Button.tsx"\n}'
      },
    },
    {
      name: 'Initiate AI Code Generation',
      method: 'POST',
      path: '/api/code-gen/generate/',
      description: 'Sends a prompt to the AI for code generation and receives streaming updates via WebSocket.',
      authentication: 'JWT',
      requestBody: {
        filename: 'ai_generate_request.json',
        language: 'json',
        code: '{\n  "project_slug": "my-first-project",\n  "prompt": "Create a new React component for a user profile page.",\n  "model": "claude-sonnet-4"\n}'
      },
      responseBody: {
        filename: 'ai_generate_response.json',
        language: 'json',
        code: '{\n  "message": "AI generation started. Connect to WebSocket for updates.",\n  "websocket_url": "wss://api.buildify.dev/ws/code-gen/my-first-project/"\n}'
      },
    },
    {
      name: 'Get Credit Balance',
      method: 'GET',
      path: '/api/credits/balance/',
      description: 'Retrieves the authenticated user\'s current credit balance.',
      authentication: 'JWT',
      responseBody: {
        filename: 'credit_balance.json',
        language: 'json',
        code: '{\n  "balance": "100.50",\n  "currency": "USD"\n}'
      },
    },
    {
      name: 'Purchase Credits',
      method: 'POST',
      path: '/api/credits/purchase/',
      description: 'Initiates a Stripe checkout session for purchasing credits.',
      authentication: 'JWT',
      requestBody: {
        filename: 'purchase_credits.json',
        language: 'json',
        code: '{\n  "package_id": 1,\n  "quantity": 1\n}'
      },
      responseBody: {
        filename: 'checkout_session.json',
        language: 'json',
        code: '{\n  "checkout_url": "https://checkout.stripe.com/pay/cs_test_..."\n}'
      },
    },
    {
      name: 'Connect GitHub Repository',
      method: 'POST',
      path: '/api/github/connect/',
      description: 'Connects a GitHub repository to a Buildify project.',
      authentication: 'JWT',
      requestBody: {
        filename: 'github_connect.json',
        language: 'json',
        code: '{\n  "project_slug": "my-first-project",\n  "repo_name": "my-github-repo",\n  "private": true\n}'
      },
      responseBody: {
        filename: 'github_repo_connected.json',
        language: 'json',
        code: '{\n  "message": "GitHub repository connected successfully",\n  "repo_url": "https://github.com/username/my-github-repo"\n}'
      },
    },
    {
      name: 'Deploy Project Preview',
      method: 'POST',
      path: '/api/deploy/preview/',
      description: 'Deploys a project to a Fly.io preview environment.',
      authentication: 'JWT',
      requestBody: {
        filename: 'deploy_preview.json',
        language: 'json',
        code: '{\n  "project_slug": "my-first-project"\n}'
      },
      responseBody: {
        filename: 'deploy_preview_response.json',
        language: 'json',
        code: '{\n  "message": "Deployment initiated",\n  "preview_url": "https://my-first-project-pr-123.fly.dev"\n}'
      },
    },
  ];

  const categories = ['All', 'Authentication', 'Projects', 'Code Generation', 'Payments', 'GitHub', 'Deployment'];

  const getCategoryEndpoints = (category: string) => {
    if (category === 'All') return endpoints;
    return endpoints.filter(endpoint => {
      if (category === 'Authentication') return endpoint.path.startsWith('/api/auth/') || endpoint.path.startsWith('/api/users/');
      if (category === 'Projects') return endpoint.path.startsWith('/api/projects/');
      if (category === 'Code Generation') return endpoint.path.startsWith('/api/code-gen/');
      if (category === 'Payments') return endpoint.path.startsWith('/api/credits/purchase/');
      if (category === 'GitHub') return endpoint.path.startsWith('/api/github/');
      if (category === 'Deployment') return endpoint.path.startsWith('/api/deploy/');
      return false;
    });
  };

  const filterEndpoints = (eps: Endpoint[]) => {
    if (!searchQuery) return eps;
    const query = searchQuery.toLowerCase();
    return eps.filter(
      (endpoint) =>
        endpoint.name.toLowerCase().includes(query) ||
        endpoint.path.toLowerCase().includes(query) ||
        endpoint.description.toLowerCase().includes(query)
    );
  };

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-4">
          <span className="gradient-primary text-gradient">API Reference</span>
        </h1>
        <p className="text-lg text-muted-foreground max-w-3xl">
          Comprehensive documentation for the Buildify REST API, including authentication, project management,
          AI code generation, and deployment endpoints.
        </p>
      </div>

      {/* Search */}
      <div className="mb-6 relative">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          type="text"
          placeholder="Search endpoints by name, path, or description..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="pl-10"
        />
      </div>

      {/* Tabs for Categories */}
      <Tabs defaultValue="All" className="w-full">
        <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 lg:grid-cols-7 mb-8">
          {categories.map((category) => (
            <TabsTrigger key={category} value={category}>
              {category}
            </TabsTrigger>
          ))}
        </TabsList>

        {categories.map((category) => {
          const eps = filterEndpoints(getCategoryEndpoints(category));
          return (
            <TabsContent key={category} value={category}>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {eps.map((endpoint) => (
                  <EndpointCard key={endpoint.path} endpoint={endpoint} />
                ))}
              </div>
              {eps.length === 0 && (
                <div className="text-center py-12 text-muted-foreground">
                  No endpoints found matching "{searchQuery}" in this category.
                </div>
              )}
            </TabsContent>
          );
        })}
      </Tabs>
    </div>
  );
}
